import {
  Folder, ExternalLink, Home, Bookmark, Star, Link, Settings, Mail, Calendar,
  FileText, BarChart3, Target, CheckCircle, AlertCircle, Clock, Search,
  Download, Upload, Code, Database, Cloud, Zap, Heart, Eye, EyeOff,
  Lock, Unlock, User, Users, Gift, Music, Camera, Play, Pause, Volume2,
  Smartphone, Monitor, HardDrive, Server, Wifi, Globe, Map, Compass,
  Trash2, Copy, Edit2, Share2, Bell, MessageSquare, PlusCircle, MinusCircle,
  ChevronRight, ChevronLeft, ChevronDown, ChevronUp, Expand, RotateCcw,
  Filter, ArrowUp, Archive, Package, Info, HelpCircle, Lightbulb, Briefcase,
  CreditCard, DollarSign, TrendingUp, PieChart, Radio, Tv, Headphones, Layers,
  Smile, Send, Phone, MapPin, Navigation, Inbox, BookOpen, Pencil, Maximize2,
  Minimize2, Grid, List, Square, Circle, Triangle, Hexagon, Slack, Github,
  Linkedin, Twitter, Facebook, Instagram, Youtube, GitBranch, GitCommit, GitPullRequest,
  Plus, Minus, X, Check, ChevronRightCircle, ChevronLeftCircle, AlertTriangle,
  ZoomIn, ZoomOut, Mic, MicOff, Volume, VolumeX, Repeat, Shuffle,
  Type, Bold, Italic, Underline, AlignLeft, AlignCenter, AlignRight,
  ListOrdered, Indent, Outdent, Wind, CloudRain, CloudSnow,
  Sun, Moon, Droplet, Umbrella, Flame, Snowflake, Percent,
  ArrowLeft, ArrowRight, ArrowDown, ArrowUpRight, ArrowUpLeft, ArrowDownRight, ArrowDownLeft,
  SkipBack, SkipForward, FastForward, Rewind, Activity, Anchor, Airplay,
  Apple, AppWindow, Award, BarChart, BarChart2, Battery, Bed, BellOff, Binoculars,
  Bluetooth, Bug, Building, Bus, Clipboard, CloudDrizzle, Coffee, Command, Cpu,
  Crosshair, ChevronsLeft, ChevronsRight, ChevronsDown, ChevronsUp, Disc,
  Edit, Edit3, Feather, File, FileCheck, FileMinus, FilePlus, FileQuestion, FileX, Film,
  Flag, Flashlight, FolderMinus, FolderOpen, FolderPlus, Focus, Frown,
  Gamepad2, Gauge, GitCompare, GitMerge, Grip,
  GripHorizontal, GripVertical, HardHat, Hash, Heading, Heading1, Heading2, Heading3,
  HeartOff, HeartHandshake, Highlighter, History, Hourglass,
  Joystick, Key, Keyboard, Landmark, Laptop, Leaf, LineChart, ListChecks,
  LockOpen, LogIn, LogOut, Luggage, MailCheck, MailMinus, MailOpen, MailPlus,
  MailQuestion, MailX, Menu, MessageCircle, Microscope, MinusSquare, MonitorOff,
  MoreHorizontal, MoreVertical, Mountain, Mouse, MousePointer, Move,
  Nfc, Octagon, PackageCheck, PackageMinus, PackagePlus, PackageX,
  Paperclip, PauseCircle, PenTool, PencilLine, PercentCircle,
  PhoneCall, PhoneMissed, PhoneOff, Pill, PinOff, Pipette, Printer,
  Puzzle, Radar, RotateCw, Shield, ShieldAlert, ShieldCheck, ShieldOff,
  ShoppingBag, ShoppingCart, Sidebar, SidebarClose, SidebarOpen, Siren,
  Sliders, Speaker, SquareCheck, SquareMinus, SquarePlus, SquareX, Stamp,
  StarHalf, StarOff, Store, Strikethrough, Subscript, Subtitles,
  Superscript, Sword, Syringe, Table, Tablet, Tag, Tags, Terminal, TestTube,
  Text, TextCursorInput, TextQuote, TextSelect, Thermometer, ThumbsDown, ThumbsUp,
  Ticket, TicketCheck, TicketMinus, TicketPlus, TicketX, Timer, TimerOff, TimerReset,
  ToggleLeft, ToggleRight, Toilet, Tornado, TrendingDown, Trophy, Truck, TvMinimalPlay, Twitch,
  Undo, Undo2, Unlink, UploadCloud, Usb, UsersRound,
  Video, VideoOff, Wallet, Watch, Wand2, Warehouse, Waves, Waypoints,
  Webhook, Wine, WineOff, Workflow, WrapText, Wrench, XCircle, XSquare, ZapOff
} from 'lucide-react';

export interface Note {
  id: string;
  content: string;
  color: string; // 背景色用 (例: 'bg-yellow-100')
  tags: string[]; // タグのリスト
  createdAt: Date;
  updatedAt: Date;
}

// メモの色オプション
export const NOTE_COLORS = [
  { name: 'デフォルト', value: 'bg-gray-50 dark:bg-slate-700', border: 'border-gray-200 dark:border-slate-600' },
  { name: '黄色', value: 'bg-yellow-100 dark:bg-yellow-900/30', border: 'border-yellow-300 dark:border-yellow-700' },
  { name: '緑', value: 'bg-green-100 dark:bg-green-900/30', border: 'border-green-300 dark:border-green-700' },
  { name: '青', value: 'bg-blue-100 dark:bg-blue-900/30', border: 'border-blue-300 dark:border-blue-700' },
  { name: 'ピンク', value: 'bg-pink-100 dark:bg-pink-900/30', border: 'border-pink-300 dark:border-pink-700' },
  { name: '紫', value: 'bg-purple-100 dark:bg-purple-900/30', border: 'border-purple-300 dark:border-purple-700' },
  { name: 'オレンジ', value: 'bg-orange-100 dark:bg-orange-900/30', border: 'border-orange-300 dark:border-orange-700' },
];

export const ICON_OPTIONS = [
  // Original icons
  { name: 'Folder', component: Folder },
  { name: 'ExternalLink', component: ExternalLink },
  { name: 'Home', component: Home },
  { name: 'Bookmark', component: Bookmark },
  { name: 'Star', component: Star },
  { name: 'Link', component: Link },
  { name: 'Settings', component: Settings },
  { name: 'Mail', component: Mail },
  { name: 'Calendar', component: Calendar },
  { name: 'FileText', component: FileText },
  { name: 'BarChart3', component: BarChart3 },
  { name: 'Target', component: Target },
  { name: 'CheckCircle', component: CheckCircle },
  { name: 'AlertCircle', component: AlertCircle },
  { name: 'Clock', component: Clock },
  { name: 'Search', component: Search },
  { name: 'Download', component: Download },
  { name: 'Upload', component: Upload },
  { name: 'Code', component: Code },
  { name: 'Database', component: Database },
  { name: 'Cloud', component: Cloud },
  { name: 'Zap', component: Zap },
  { name: 'Heart', component: Heart },
  { name: 'Eye', component: Eye },
  { name: 'EyeOff', component: EyeOff },
  { name: 'Lock', component: Lock },
  { name: 'Unlock', component: Unlock },
  { name: 'User', component: User },
  { name: 'Users', component: Users },
  { name: 'Gift', component: Gift },
  { name: 'Music', component: Music },
  { name: 'Camera', component: Camera },
  { name: 'Play', component: Play },
  { name: 'Pause', component: Pause },
  { name: 'Volume2', component: Volume2 },
  { name: 'Smartphone', component: Smartphone },
  { name: 'Monitor', component: Monitor },
  { name: 'HardDrive', component: HardDrive },
  { name: 'Server', component: Server },
  { name: 'Wifi', component: Wifi },
  { name: 'Globe', component: Globe },
  { name: 'Map', component: Map },
  { name: 'Compass', component: Compass },
  { name: 'Trash2', component: Trash2 },
  { name: 'Copy', component: Copy },
  { name: 'Edit2', component: Edit2 },
  { name: 'Share2', component: Share2 },
  { name: 'Bell', component: Bell },
  { name: 'MessageSquare', component: MessageSquare },
  { name: 'PlusCircle', component: PlusCircle },
  { name: 'MinusCircle', component: MinusCircle },
  { name: 'ChevronRight', component: ChevronRight },
  { name: 'ChevronLeft', component: ChevronLeft },
  { name: 'ChevronDown', component: ChevronDown },
  { name: 'ChevronUp', component: ChevronUp },
  { name: 'Expand', component: Expand },
  { name: 'RotateCcw', component: RotateCcw },
  { name: 'Filter', component: Filter },
  { name: 'ArrowUp', component: ArrowUp },
  { name: 'Archive', component: Archive },
  { name: 'Package', component: Package },
  { name: 'Info', component: Info },
  { name: 'HelpCircle', component: HelpCircle },
  { name: 'Lightbulb', component: Lightbulb },
  { name: 'Briefcase', component: Briefcase },
  { name: 'CreditCard', component: CreditCard },
  { name: 'DollarSign', component: DollarSign },
  { name: 'TrendingUp', component: TrendingUp },
  { name: 'PieChart', component: PieChart },
  { name: 'Radio', component: Radio },
  { name: 'Tv', component: Tv },
  { name: 'Headphones', component: Headphones },
  { name: 'Layers', component: Layers },
  { name: 'Smile', component: Smile },
  { name: 'Send', component: Send },
  { name: 'Phone', component: Phone },
  { name: 'MapPin', component: MapPin },
  { name: 'Navigation', component: Navigation },
  { name: 'Inbox', component: Inbox },
  { name: 'BookOpen', component: BookOpen },
  { name: 'Pencil', component: Pencil },
  { name: 'Maximize2', component: Maximize2 },
  { name: 'Minimize2', component: Minimize2 },
  { name: 'Grid', component: Grid },
  { name: 'List', component: List },
  { name: 'Square', component: Square },
  { name: 'Circle', component: Circle },
  { name: 'Triangle', component: Triangle },
  { name: 'Hexagon', component: Hexagon },
  { name: 'Slack', component: Slack },
  { name: 'Github', component: Github },
  { name: 'Linkedin', component: Linkedin },
  { name: 'Twitter', component: Twitter },
  { name: 'Facebook', component: Facebook },
  { name: 'Instagram', component: Instagram },
  { name: 'Youtube', component: Youtube },
  { name: 'GitBranch', component: GitBranch },
  { name: 'GitCommit', component: GitCommit },
  { name: 'GitPullRequest', component: GitPullRequest },
  { name: 'Plus', component: Plus },
  { name: 'Minus', component: Minus },
  { name: 'X', component: X },
  { name: 'Check', component: Check },
  { name: 'ChevronRightCircle', component: ChevronRightCircle },
  { name: 'ChevronLeftCircle', component: ChevronLeftCircle },
  { name: 'AlertTriangle', component: AlertTriangle },
  { name: 'ZoomIn', component: ZoomIn },
  { name: 'ZoomOut', component: ZoomOut },
  { name: 'Mic', component: Mic },
  { name: 'MicOff', component: MicOff },
  { name: 'Volume', component: Volume },
  { name: 'VolumeX', component: VolumeX },
  { name: 'Repeat', component: Repeat },
  { name: 'Shuffle', component: Shuffle },
  { name: 'Type', component: Type },
  { name: 'Bold', component: Bold },
  { name: 'Italic', component: Italic },
  { name: 'Underline', component: Underline },
  { name: 'AlignLeft', component: AlignLeft },
  { name: 'AlignCenter', component: AlignCenter },
  { name: 'AlignRight', component: AlignRight },
  { name: 'ListOrdered', component: ListOrdered },
  { name: 'Indent', component: Indent },
  { name: 'Outdent', component: Outdent },
  { name: 'Wind', component: Wind },
  { name: 'CloudRain', component: CloudRain },
  { name: 'CloudSnow', component: CloudSnow },
  { name: 'Sun', component: Sun },
  { name: 'Moon', component: Moon },
  { name: 'Droplet', component: Droplet },
  { name: 'Umbrella', component: Umbrella },
  { name: 'Flame', component: Flame },
  { name: 'Snowflake', component: Snowflake },
  { name: 'Percent', component: Percent },

  // Additional arrows
  { name: 'ArrowLeft', component: ArrowLeft },
  { name: 'ArrowRight', component: ArrowRight },
  { name: 'ArrowDown', component: ArrowDown },
  { name: 'ArrowUpRight', component: ArrowUpRight },
  { name: 'ArrowUpLeft', component: ArrowUpLeft },
  { name: 'ArrowDownRight', component: ArrowDownRight },
  { name: 'ArrowDownLeft', component: ArrowDownLeft },

  // Media & playback
  { name: 'SkipBack', component: SkipBack },
  { name: 'SkipForward', component: SkipForward },
  { name: 'FastForward', component: FastForward },
  { name: 'Rewind', component: Rewind },
  { name: 'Video', component: Video },
  { name: 'VideoOff', component: VideoOff },

  // Navigation
  { name: 'Activity', component: Activity },
  { name: 'Anchor', component: Anchor },
  { name: 'Airplay', component: Airplay },

  // Hardware & devices
  { name: 'Apple', component: Apple },
  { name: 'AppWindow', component: AppWindow },
  { name: 'Award', component: Award },
  { name: 'BarChart', component: BarChart },
  { name: 'BarChart2', component: BarChart2 },
  { name: 'Battery', component: Battery },
  { name: 'Bed', component: Bed },
  { name: 'BellOff', component: BellOff },
  { name: 'Binoculars', component: Binoculars },
  { name: 'Bluetooth', component: Bluetooth },
  { name: 'Bug', component: Bug },
  { name: 'Building', component: Building },
  { name: 'Bus', component: Bus },
  { name: 'Clipboard', component: Clipboard },
  { name: 'CloudDrizzle', component: CloudDrizzle },
  { name: 'Coffee', component: Coffee },
  { name: 'Command', component: Command },
  { name: 'Cpu', component: Cpu },
  { name: 'Crosshair', component: Crosshair },

  // Chevrons & expandable
  { name: 'ChevronsLeft', component: ChevronsLeft },
  { name: 'ChevronsRight', component: ChevronsRight },
  { name: 'ChevronsDown', component: ChevronsDown },
  { name: 'ChevronsUp', component: ChevronsUp },
  { name: 'Disc', component: Disc },

  // File & document
  { name: 'Edit', component: Edit },
  { name: 'Edit3', component: Edit3 },
  { name: 'Feather', component: Feather },
  { name: 'File', component: File },
  { name: 'FileCheck', component: FileCheck },
  { name: 'FileMinus', component: FileMinus },
  { name: 'FilePlus', component: FilePlus },
  { name: 'FileQuestion', component: FileQuestion },
  { name: 'FileX', component: FileX },
  { name: 'Film', component: Film },
  { name: 'Flag', component: Flag },
  { name: 'Flashlight', component: Flashlight },
  { name: 'FolderMinus', component: FolderMinus },
  { name: 'FolderOpen', component: FolderOpen },
  { name: 'FolderPlus', component: FolderPlus },
  { name: 'Focus', component: Focus },
  { name: 'Frown', component: Frown },

  // Games & interactive
  { name: 'Gamepad2', component: Gamepad2 },
  { name: 'Gauge', component: Gauge },
  { name: 'GitCompare', component: GitCompare },
  { name: 'GitMerge', component: GitMerge },
  { name: 'Grip', component: Grip },
  { name: 'GripHorizontal', component: GripHorizontal },
  { name: 'GripVertical', component: GripVertical },

  // Hardware & tools
  { name: 'HardHat', component: HardHat },
  { name: 'Hash', component: Hash },
  { name: 'Heading', component: Heading },
  { name: 'Heading1', component: Heading1 },
  { name: 'Heading2', component: Heading2 },
  { name: 'Heading3', component: Heading3 },
  { name: 'HeartOff', component: HeartOff },
  { name: 'HeartHandshake', component: HeartHandshake },
  { name: 'Highlighter', component: Highlighter },
  { name: 'History', component: History },
  { name: 'Hourglass', component: Hourglass },

  // Additional utilities
  { name: 'Joystick', component: Joystick },
  { name: 'Key', component: Key },
  { name: 'Keyboard', component: Keyboard },
  { name: 'Landmark', component: Landmark },
  { name: 'Laptop', component: Laptop },
  { name: 'Leaf', component: Leaf },
  { name: 'LineChart', component: LineChart },
  { name: 'ListChecks', component: ListChecks },
  { name: 'LockOpen', component: LockOpen },
  { name: 'LogIn', component: LogIn },
  { name: 'LogOut', component: LogOut },
  { name: 'Luggage', component: Luggage },

  // Mail related
  { name: 'MailCheck', component: MailCheck },
  { name: 'MailMinus', component: MailMinus },
  { name: 'MailOpen', component: MailOpen },
  { name: 'MailPlus', component: MailPlus },
  { name: 'MailQuestion', component: MailQuestion },
  { name: 'MailX', component: MailX },

  // More navigation
  { name: 'Menu', component: Menu },
  { name: 'MessageCircle', component: MessageCircle },
  { name: 'Microscope', component: Microscope },
  { name: 'MinusSquare', component: MinusSquare },
  { name: 'MonitorOff', component: MonitorOff },
  { name: 'MoreHorizontal', component: MoreHorizontal },
  { name: 'MoreVertical', component: MoreVertical },
  { name: 'Mountain', component: Mountain },
  { name: 'Mouse', component: Mouse },
  { name: 'MousePointer', component: MousePointer },
  { name: 'Move', component: Move },

  // Network & communication
  { name: 'Nfc', component: Nfc },
  { name: 'Octagon', component: Octagon },

  // Packages
  { name: 'PackageCheck', component: PackageCheck },
  { name: 'PackageMinus', component: PackageMinus },
  { name: 'PackagePlus', component: PackagePlus },
  { name: 'PackageX', component: PackageX },
  { name: 'Paperclip', component: Paperclip },
  { name: 'PauseCircle', component: PauseCircle },
  { name: 'PenTool', component: PenTool },
  { name: 'PencilLine', component: PencilLine },
  { name: 'PercentCircle', component: PercentCircle },

  // Phone & communication
  { name: 'PhoneCall', component: PhoneCall },
  { name: 'PhoneMissed', component: PhoneMissed },
  { name: 'PhoneOff', component: PhoneOff },
  { name: 'Pill', component: Pill },
  { name: 'PinOff', component: PinOff },
  { name: 'Pipette', component: Pipette },
  { name: 'Printer', component: Printer },
  { name: 'Puzzle', component: Puzzle },

  // Radar & rotating
  { name: 'Radar', component: Radar },
  { name: 'RotateCw', component: RotateCw },

  // Security & shields
  { name: 'Shield', component: Shield },
  { name: 'ShieldAlert', component: ShieldAlert },
  { name: 'ShieldCheck', component: ShieldCheck },
  { name: 'ShieldOff', component: ShieldOff },

  // Shopping
  { name: 'ShoppingBag', component: ShoppingBag },
  { name: 'ShoppingCart', component: ShoppingCart },

  // Sidebar
  { name: 'Sidebar', component: Sidebar },
  { name: 'SidebarClose', component: SidebarClose },
  { name: 'SidebarOpen', component: SidebarOpen },
  { name: 'Siren', component: Siren },
  { name: 'Sliders', component: Sliders },
  { name: 'Speaker', component: Speaker },

  // Squares
  { name: 'SquareCheck', component: SquareCheck },
  { name: 'SquareMinus', component: SquareMinus },
  { name: 'SquarePlus', component: SquarePlus },
  { name: 'SquareX', component: SquareX },
  { name: 'Stamp', component: Stamp },

  // Star & rating
  { name: 'StarHalf', component: StarHalf },
  { name: 'StarOff', component: StarOff },
  { name: 'Store', component: Store },

  // Text formatting
  { name: 'Strikethrough', component: Strikethrough },
  { name: 'Subscript', component: Subscript },
  { name: 'Subtitles', component: Subtitles },
  { name: 'Superscript', component: Superscript },
  { name: 'Sword', component: Sword },
  { name: 'Syringe', component: Syringe },

  // Table & data
  { name: 'Table', component: Table },
  { name: 'Tablet', component: Tablet },
  { name: 'Tag', component: Tag },
  { name: 'Tags', component: Tags },
  { name: 'Terminal', component: Terminal },
  { name: 'TestTube', component: TestTube },
  { name: 'Text', component: Text },
  { name: 'TextCursorInput', component: TextCursorInput },
  { name: 'TextQuote', component: TextQuote },
  { name: 'TextSelect', component: TextSelect },
  { name: 'Thermometer', component: Thermometer },
  { name: 'ThumbsDown', component: ThumbsDown },
  { name: 'ThumbsUp', component: ThumbsUp },

  // Tickets & entries
  { name: 'Ticket', component: Ticket },
  { name: 'TicketCheck', component: TicketCheck },
  { name: 'TicketMinus', component: TicketMinus },
  { name: 'TicketPlus', component: TicketPlus },
  { name: 'TicketX', component: TicketX },
  { name: 'Timer', component: Timer },
  { name: 'TimerOff', component: TimerOff },
  { name: 'TimerReset', component: TimerReset },

  // Toggle switches
  { name: 'ToggleLeft', component: ToggleLeft },
  { name: 'ToggleRight', component: ToggleRight },
  { name: 'Toilet', component: Toilet },
  { name: 'Tornado', component: Tornado },

  // Trending & growth
  { name: 'TrendingDown', component: TrendingDown },
  { name: 'Trophy', component: Trophy },
  { name: 'Truck', component: Truck },
  { name: 'TvMinimalPlay', component: TvMinimalPlay },
  { name: 'Twitch', component: Twitch },

  // Undo & actions
  { name: 'Undo', component: Undo },
  { name: 'Undo2', component: Undo2 },
  { name: 'Unlink', component: Unlink },
  { name: 'UploadCloud', component: UploadCloud },
  { name: 'Usb', component: Usb },
  { name: 'UsersRound', component: UsersRound },

  // Vimeo & video
  { name: 'Wallet', component: Wallet },
  { name: 'Watch', component: Watch },
  { name: 'Wand2', component: Wand2 },
  { name: 'Warehouse', component: Warehouse },
  { name: 'Waves', component: Waves },
  { name: 'Waypoints', component: Waypoints },
  { name: 'Webhook', component: Webhook },
  { name: 'Wine', component: Wine },
  { name: 'WineOff', component: WineOff },
  { name: 'Workflow', component: Workflow },
  { name: 'WrapText', component: WrapText },
  { name: 'Wrench', component: Wrench },
  { name: 'XCircle', component: XCircle },
  { name: 'XSquare', component: XSquare },
  { name: 'ZapOff', component: ZapOff },
];
