import { 
  Folder, MessageSquare, FileText, ChevronRight, Plus, X, Trash2, Edit2,
  ExternalLink, BookOpen, Code, Globe, Mail, User, Star, Heart, Zap, 
  Home, Settings, Calendar, Search, Clock, ChevronDown, FolderPlus,
  Image, Music, Video, Database, Server, Terminal, Cpu, HardDrive,
  Wifi, Lock, Unlock, Key, Shield, AlertCircle, CheckCircle, Info,
  Cloud, CloudRain, Sun, Moon, Briefcase, ShoppingCart, CreditCard,
  Gift, Award, Target, Flag, Bookmark, Tag, PenTool, Palette,
  Camera, Film, Mic, Headphones, Archive, Package, Inbox, Send,
  Download, Upload, Printer, Monitor, Smartphone, Tablet, Laptop,
  Chrome, Github, Linkedin, Twitter, Facebook, Instagram, Youtube,
  FileSpreadsheet, FilePieChart, FileBarChart, Presentation, File,
  Files, FolderOpen, ClipboardList, Clipboard, ClipboardCheck,
  Users, UserPlus, Building, Building2, TrendingUp, TrendingDown,
  PieChart, BarChart, BarChart2, BarChart3, LineChart, Activity,
  DollarSign, Receipt, Calculator, Percent, FileSignature, FileCheck,
  Trees
} from 'lucide-react';

export const ICON_OPTIONS = [
  { name: 'Folder', component: Folder },
  { name: 'ExternalLink', component: ExternalLink },
  { name: 'BookOpen', component: BookOpen },
  { name: 'Code', component: Code },
  { name: 'Globe', component: Globe },
  { name: 'Mail', component: Mail },
  { name: 'User', component: User },
  { name: 'Star', component: Star },
  { name: 'Heart', component: Heart },
  { name: 'Zap', component: Zap },
  { name: 'Home', component: Home },
  { name: 'Trees', component: Trees },
  { name: 'Settings', component: Settings },
  { name: 'Calendar', component: Calendar },
  { name: 'Search', component: Search },
  { name: 'Clock', component: Clock },
  // Office & Documents
  { name: 'FileText', component: FileText },
  { name: 'File', component: File },
  { name: 'Files', component: Files },
  { name: 'FileSpreadsheet', component: FileSpreadsheet },
  { name: 'FilePieChart', component: FilePieChart },
  { name: 'FileBarChart', component: FileBarChart },
  { name: 'FileSignature', component: FileSignature },
  { name: 'FileCheck', component: FileCheck },
  { name: 'Presentation', component: Presentation },
  { name: 'FolderOpen', component: FolderOpen },
  { name: 'ClipboardList', component: ClipboardList },
  { name: 'Clipboard', component: Clipboard },
  { name: 'ClipboardCheck', component: ClipboardCheck },
  // Business & Teams
  { name: 'Briefcase', component: Briefcase },
  { name: 'Users', component: Users },
  { name: 'UserPlus', component: UserPlus },
  { name: 'Building', component: Building },
  { name: 'Building2', component: Building2 },
  // Analytics & Charts
  { name: 'TrendingUp', component: TrendingUp },
  { name: 'TrendingDown', component: TrendingDown },
  { name: 'PieChart', component: PieChart },
  { name: 'BarChart', component: BarChart },
  { name: 'BarChart2', component: BarChart2 },
  { name: 'BarChart3', component: BarChart3 },
  { name: 'LineChart', component: LineChart },
  { name: 'Activity', component: Activity },
  // Finance
  { name: 'DollarSign', component: DollarSign },
  { name: 'Receipt', component: Receipt },
  { name: 'Calculator', component: Calculator },
  { name: 'Percent', component: Percent },
  { name: 'CreditCard', component: CreditCard },
  // Media
  { name: 'Image', component: Image },
  { name: 'Music', component: Music },
  { name: 'Video', component: Video },
  { name: 'Camera', component: Camera },
  { name: 'Film', component: Film },
  { name: 'Mic', component: Mic },
  { name: 'Headphones', component: Headphones },
  // Tech
  { name: 'Database', component: Database },
  { name: 'Server', component: Server },
  { name: 'Terminal', component: Terminal },
  { name: 'Cpu', component: Cpu },
  { name: 'HardDrive', component: HardDrive },
  { name: 'Wifi', component: Wifi },
  // Security
  { name: 'Lock', component: Lock },
  { name: 'Unlock', component: Unlock },
  { name: 'Key', component: Key },
  { name: 'Shield', component: Shield },
  // Status
  { name: 'AlertCircle', component: AlertCircle },
  { name: 'CheckCircle', component: CheckCircle },
  { name: 'Info', component: Info },
  // Other
  { name: 'Cloud', component: Cloud },
  { name: 'CloudRain', component: CloudRain },
  { name: 'Sun', component: Sun },
  { name: 'Moon', component: Moon },
  { name: 'ShoppingCart', component: ShoppingCart },
  { name: 'Gift', component: Gift },
  { name: 'Award', component: Award },
  { name: 'Target', component: Target },
  { name: 'Flag', component: Flag },
  { name: 'Bookmark', component: Bookmark },
  { name: 'Tag', component: Tag },
  { name: 'PenTool', component: PenTool },
  { name: 'Palette', component: Palette },
  { name: 'Archive', component: Archive },
  { name: 'Package', component: Package },
  { name: 'Inbox', component: Inbox },
  { name: 'Send', component: Send },
  { name: 'Download', component: Download },
  { name: 'Upload', component: Upload },
  { name: 'Printer', component: Printer },
  { name: 'Monitor', component: Monitor },
  { name: 'Smartphone', component: Smartphone },
  { name: 'Tablet', component: Tablet },
  { name: 'Laptop', component: Laptop },
  { name: 'Chrome', component: Chrome },
  { name: 'Github', component: Github },
  { name: 'Linkedin', component: Linkedin },
  { name: 'Twitter', component: Twitter },
  { name: 'Facebook', component: Facebook },
  { name: 'Instagram', component: Instagram },
  { name: 'Youtube', component: Youtube },
];
